# ===================================================================
# |                         超时与性能设置                           |
# ===================================================================

# 节点 HTTP 连通性测试的超时时间 (毫秒)
ProxyTestTimeout: 5000

# `git ls-remote` 命令的超时时间 (毫秒)
GitLsRemoteTimeout: 20000

# `git clone` 命令的超时时间 (毫秒)
GitCloneTimeout: 900000 # 15 分钟

# `git pull` / `git fetch` 等更新命令的超时时间 (毫秒)
GitPullTimeout: 120000 # 2 分钟

# 克隆深度
GitCloneDepth: 1


# ===================================================================
# |                           GitHub 加速节点                         |
# ===================================================================

Proxies:
  # - { name: "Moeyy",         priority: 0,    url: "https://github.moeyy.xyz" }
  - { name: "Ghfast",        priority: 10,   url: "https://ghfast.top" }
  # - { name: "FastGit",       priority: 12,   url: "https://hub.fastgit.xyz" }
  - { name: "GhproxyCom",    priority: 18,   url: "https://gh-proxy.com" }
  - { name: "FastlyCDN",     priority: 25,   url: "https://cdn.gh-proxy.com" }
  - { name: "UiGhproxy",     priority: 28,   url: "https://ui.ghproxy.cc" }
  # - { name: "GhproxyGo",     priority: 35,   url: "https://ghproxy.1888866.xyz" }
  - { name: "GhddlcTop",     priority: 80,   url: "https://gh.ddlc.top" }
  
  # --- 特殊规则节点 ---
  - { name: "Mirror",        priority: 310,  url: "https://hub.gitmirror.com" }
  - { name: "GitHub",        priority: 500,  url: "https://github.com" }
