# ===================================================================
# |                           辅助工具                               |
# ===================================================================
# --- 内容过滤开关 ---
# true: 显示这类图片, false: 过滤掉这类图片
Filter:
  Ai: true
  EasterEgg: true
  Layout: true # 横屏图
  
# 官方立绘同步-额外从 miao-plugin 同步官方角色立绘
OfficialSplashArt: false

# 原图拦截-发送 #原图 并引用一张来自咕咕牛的面板图时，是否将其拦截并以安全的方式（合并转发）发送，防止被腾讯屏蔽。
SleeperAgentSwitch: true

# ===================================================================
# |                          性能与模式                              |
# ===================================================================
# 'Batch': 高速并发模式，适合大多数情况。
# 'Serial': 串行低负载模式，当系统资源紧张时开启，会增加指令CD并进行系统健康检查。
ExecutionMode: 'Batch'

# 负载等级 (仅在低负载模式开启时生效)
# 1: 标准 (15秒CD, 阈值宽松)
# 2: 保守 (30秒CD, 阈值中等)
# 3: 极致 (60秒CD, 阈值严格)-
LoadLevel: 1

# 渲染精度 (单位: %)
# 调整所有由本插件生成的图片的分辨率。范围 100-500。
# 较高的值会使图片更清晰，但生成速度更慢，图片文件也更大。
RenderScale: 100

# ===================================================================
# |                           定时任务                               |
# ===================================================================
#咕咕牛图库更新定时任务
UpdateCron: "0 0 */12 * * *"